version: '3'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tes
    ports:
      - 5432:5432
    networks:
      - app_network
    restart: unless-stopped

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    depends_on:
      - db
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://postgres:postgres@172.18.0.2:5432/tes"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge